### ISSUE TITLE
Add default resilience4j config

### ISSUE THREAD

**Issue by timpamungkas** [ferdinalcandra/DEVSCHEDULER#16]
```
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 30s
```
