### ISSUE TITLE
Configuration naming

### ISSUE THREAD

**Issue by timpamungkasudemy** [ferdinalcandra/DEVSCHEDULER#7]
kalau untuk naming custom, bukan spring, jangan taruh di bawah key `spring`.

E.g. di `TempDataDbConfig` ini ambilnya dari key `spring.datasource.db-temp`.  
Pisahkan antara bawaan spring (`application.yml, bootstrap.yml`) dan custom app, di beda file dan beda key.

**Comment by timpamungkasudemy** [comment]
Misalnya, based on config yang ada

di folder **conf** (bukan package id.co.bfi.dmsuplpoad....conf) buat file documentum.yml, dengan key

```yaml
documentum:
  datasource:
    db-temp:
      # key
    db-master:
      # key
  query:
    # key
  share-folder:
```
